spring:
  docker:
    compose:
      enabled: true
      file: ./worker/compose.yaml
  jpa:
    open-in-view: false

kafka:
  consumer:
    bootstrap-servers: localhost:9092
    coupon-create-topic: coupon-create
    group-id: group_1
