spring:
  docker:
    compose:
      enabled: true
      file: ./api/compose.yaml
  jpa:
    open-in-view: false

kafka:
  producer:
    bootstrap-servers: localhost:9092
    coupon-create-topic: coupon-create
